# platform :ios, '9.0'

target 'Kuaidi' do
 pod 'AFNetworking', '~>3.2.1'
 pod 'SDCycleScrollView', '~> 1.80'
 pod 'MJRefresh', '~> 3.1.12'
 pod 'MJExtension', '~> 3.0.13'
 pod 'SVProgressHUD', '~> 2.0.3'
 pod 'Masonry','~> 0.6.3'
 pod 'MBProgressHUD', '~> 1.0.0'
 pod 'SDWebImage'
 pod 'CRBoxInputView', '1.1.2'
 pod 'PGPickerView'
end
